package chatmodule;


/**
* chatmodule/ClientConnectionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public abstract class ClientConnectionPOA extends org.omg.PortableServer.Servant
 implements chatmodule.ClientConnectionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_mbx", new java.lang.Integer (0));
    _methods.put ("_set_mbx", new java.lang.Integer (1));
    _methods.put ("connect", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chatmodule/ClientConnection/_get_mbx
       {
         chatmodule.MessageBox $result = null;
         $result = this.mbx ();
         out = $rh.createReply();
         chatmodule.MessageBoxHelper.write (out, $result);
         break;
       }

       case 1:  // chatmodule/ClientConnection/_set_mbx
       {
         chatmodule.MessageBox newMbx = chatmodule.MessageBoxHelper.read (in);
         this.mbx (newMbx);
         out = $rh.createReply();
         break;
       }

       case 2:  // chatmodule/ClientConnection/connect
       {
         String nickname = in.read_string ();
         chatmodule.MessageBox rcv = chatmodule.MessageBoxHelper.read (in);
         chatmodule.MessageBox $result = null;
         $result = this.connect (nickname, rcv);
         out = $rh.createReply();
         chatmodule.MessageBoxHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chatmodule/ClientConnection:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientConnection _this() 
  {
    return ClientConnectionHelper.narrow(
    super._this_object());
  }

  public ClientConnection _this(org.omg.CORBA.ORB orb) 
  {
    return ClientConnectionHelper.narrow(
    super._this_object(orb));
  }


} // class ClientConnectionPOA
