package chatmodule;

/**
* chatmodule/ClientConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public final class ClientConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.ClientConnection value = null;

  public ClientConnectionHolder ()
  {
  }

  public ClientConnectionHolder (chatmodule.ClientConnection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ClientConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ClientConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ClientConnectionHelper.type ();
  }

}
