package chatmodule;


/**
* chatmodule/ClientManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public abstract class ClientManagerPOA extends org.omg.PortableServer.Servant
 implements chatmodule.ClientManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("initClients", new java.lang.Integer (0));
    _methods.put ("addClient", new java.lang.Integer (1));
    _methods.put ("remClient", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chatmodule/ClientManager/initClients
       {
         String clients[] = chatmodule.ClientsHelper.read (in);
         this.initClients (clients);
         out = $rh.createReply();
         break;
       }

       case 1:  // chatmodule/ClientManager/addClient
       {
         String client = in.read_string ();
         this.addClient (client);
         out = $rh.createReply();
         break;
       }

       case 2:  // chatmodule/ClientManager/remClient
       {
         String client = in.read_string ();
         this.remClient (client);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chatmodule/ClientManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientManager _this() 
  {
    return ClientManagerHelper.narrow(
    super._this_object());
  }

  public ClientManager _this(org.omg.CORBA.ORB orb) 
  {
    return ClientManagerHelper.narrow(
    super._this_object(orb));
  }


} // class ClientManagerPOA
