package chatmodule;


/**
* chatmodule/ClientManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public interface ClientManagerOperations 
{
  void initClients (String[] clients);
  void addClient (String client);
  void remClient (String client);
} // interface ClientManagerOperations
