package chatmodule;

/**
* chatmodule/ClientManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public final class ClientManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.ClientManager value = null;

  public ClientManagerHolder ()
  {
  }

  public ClientManagerHolder (chatmodule.ClientManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ClientManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ClientManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ClientManagerHelper.type ();
  }

}
