package chatmodule;


/**
* chatmodule/MessageBoxPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public abstract class MessageBoxPOA extends org.omg.PortableServer.Servant
 implements chatmodule.MessageBoxOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_message", new java.lang.Integer (0));
    _methods.put ("_set_message", new java.lang.Integer (1));
    _methods.put ("receive", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chatmodule/MessageBox/_get_message
       {
         String $result = null;
         $result = this.message ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // chatmodule/MessageBox/_set_message
       {
         String newMessage = in.read_string ();
         this.message (newMessage);
         out = $rh.createReply();
         break;
       }

       case 2:  // chatmodule/MessageBox/receive
       {
         String message = in.read_string ();
         this.receive (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chatmodule/MessageBox:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MessageBox _this() 
  {
    return MessageBoxHelper.narrow(
    super._this_object());
  }

  public MessageBox _this(org.omg.CORBA.ORB orb) 
  {
    return MessageBoxHelper.narrow(
    super._this_object(orb));
  }


} // class MessageBoxPOA
