package chatmodule;

/**
* chatmodule/ServerConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public final class ServerConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.ServerConnection value = null;

  public ServerConnectionHolder ()
  {
  }

  public ServerConnectionHolder (chatmodule.ServerConnection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ServerConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ServerConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ServerConnectionHelper.type ();
  }

}
