package chatmodule;


/**
* chatmodule/ServerConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 27 CET
*/

public interface ServerConnectionOperations 
{
  String[] client ();
  void client (String[] newClient);
  void connect (String nickname, chatmodule.ClientConnection cnx, chatmodule.ClientManager mgr);
  void disconnect (String nickname);
  chatmodule.ClientConnection getClient (String nickname);
} // interface ServerConnectionOperations
